### ISSUE TITLE
Unused css file in starter code that can be potentially misleading

### ISSUE THREAD

**Issue by hanameee** [vercel/next-learn#109]
Hi. Thanks for the great tutorial 👏

**1. Unused css file in starter code**
There is `globals.css` file in `/styles` directory from the very first starter [learn-starter](https://github.com/vercel/next-learn/blob/master/basics/learn-starter/styles/globals.css), all the way through [assets-metadata-css-starter](https://github.com/vercel/next-learn/blob/fee5818823fcad3f55612177702e777e229a82a9/basics/assets-metadata-css-starter/styles/globals.css).

However the only css file that is imported & used in those starters is `styles/Home.module.css`, not `styles/globals.css`.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/25149664/210251327-8abc805f-d86a-4862-8a76-74eb445c71d7.png">

Are there any reasons that the file (globals.css) is included in those starters despite the fact it is not used?🤔

**2. Potentially misleading guide**

In addition, [Assets, Metadata, and CSS](https://nextjs.org/learn/basics/assets-metadata-css/css-styling) tutorial mentions the presence of `styles` directory (+ and unused `/globals.css` file).
<img width="500" alt="image" src="https://user-images.githubusercontent.com/25149664/210251546-daaff8f3-d46d-4b78-8d1c-c153e44daf57.png">

Although the starter used in tutorial already have `styles` directory as mentioned, tutorial guides us to create `styles` directory.
<img width="500" alt="image" src="https://user-images.githubusercontent.com/25149664/210252137-3676012f-253a-4734-adf8-5e9187e2ef2c.png">

And at this point I was confused, since I already got `globals.css` file but tutorial guides me to create `global.css` which seems like a typo! (considering similarity of the name for those 2 file)

After this [Assets, Metadata, and CSS](https://nextjs.org/learn/basics/assets-metadata-css/css-styling) tutorial, the unused `globals.css` file is gone, and only `global.css` file (that is used in `pages/_app.js`) remains.

<img width="500" alt="image" src="https://user-images.githubusercontent.com/25149664/210253526-1678c057-2f40-4993-a5e2-10e22dad6b38.png">

---

So, my point is...

- Is there any reason that unused `globals.css` exists?
- If not, it would be nice and clear if it's removed from starters, and also from tutorial.

**Comment by Pannu786** [comment]
And I thought I was the only one who was facing this issue..

**Comment by jmmarco** [comment]
I think that removal of the global style file might be an option, since like @hanameee pointed out, it's not mentioned till later chapters. Another option would be just to rename the conflicting file, since it is simply a file name inconsistency. It'll still be present in the first chapters, but at least the name would be the same for later chapters.

In any case, we would want to consult @manovotny to see what he has to say.

Here's my findings:

- "[Create a Next.js App](https://github.com/vercel/next-learn/tree/main/basics/learn-starter)" code creates `styles/globals.css` file
- "[Navigate Between Pages](https://github.com/vercel/next-learn/blob/main/basics/navigate-between-pages-starter/styles/globals.css) code creates `styles/globals.css` file
- "[Assets, Metadata, and CSS](https://github.com/vercel/next-learn/tree/main/basics/assets-metadata-css-starter)" code creates a `styles/global.css` file
- The remaining starter code chapters all use the singular naming convention `styles/global.css`

Based on this information, the simplest approach is to rename the filename inside for the first two starter code templates. I'll go ahead and open a PR to get things rolling 👌
