### ISSUE TITLE
Ch. 6: Cannot find name 'totalPaidInvoices', build failure

### ISSUE THREAD

**Issue by julianriise** [vercel/next-learn#251]
Vercel build failed. Tried to build locally, same error:

<img width="749" alt="Screenshot 2023-10-28 at 00 16 57" src="https://github.com/vercel/next-learn/assets/77626314/0dab5df7-8865-48af-96f9-c6884687fe9f">

**Comment by jchlu** [comment]
Problematic section is commented out in current version of the [starter-example code](https://github.com/vercel/next-learn/blob/9b33959335fc3f970bd6fae1452936c686064388/dashboard/starter-example/app/ui/dashboard/cards.tsx#L19-L28)

**Comment by delbaoliveira** [comment]
Thank you @jchlu 🙏🏼

**Comment by beckrecca** [comment]
Commenting that for me the fix was to set a blank `value=""` on the Cards in CardWrapper in order to deploy this to Vercel. The comments in this thread didn't help me fix it.

https://github.com/beckrecca/pReactice/commit/552e6e835baca69e818ea55d23804d706d748793

**Comment by beckrecca** [comment]
I figured out the inconsistency that causes this error on deployment: Later on in Chapter 9 (https://nextjs.org/learn/dashboard-app/streaming) you import `fetchCardData` into the `cards.tsx` file; however BEFORE you do that, the values `totalPaidInvoices`, `totalPendingInvoices`, `numberOfInvoices` are undefined (because that data is fetched/defined in `page.tsx` so Vercel refuses to deploy. Why this works locally I'm not sure, but Vercel is evidently stricter.
