### ISSUE TITLE
chapter 7 - charts not displaying -> console errors

### ISSUE THREAD

**Issue by tomas99batista** [vercel/next-learn#374]
![image](https://github.com/vercel/next-learn/assets/34144094/ee9f9ef9-d451-4696-8a4c-476606ba4900)

`backend.bundle.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'current')
    at backend.bundle.js:1:128442
    at backend.bundle.js:1:128598
    at backend.bundle.js:1:127404
    at Object.next (backend.bundle.js:1:127509)
    at backend.bundle.js:1:126424
    at new Promise (<anonymous>)
    at C (backend.bundle.js:1:126169)
    at backend.bundle.js:1:128313
    at o (backend.bundle.js:1:128122)`

**Comment by tomas99batista** [comment]
could it be a version problem?

**Comment by StephDietz** [comment]
Hi @tomas99batista, thanks for the feedback! This can be due to a couple of things. First, make sure all of your environment variables were copied over correctly. You should have the following in your .env file:
```
POSTGRES_URL=
POSTGRES_PRISMA_URL=
POSTGRES_URL_NON_POOLING=
POSTGRES_USER=
POSTGRES_HOST=
POSTGRES_PASSWORD=
POSTGRES_DATABASE=
```
Next, ensure that you successfully seeded data into your tables in the previous step. Check out [this section](https://nextjs.org/learn/dashboard-app/setting-up-your-database#exploring-your-database) if you need help exploring your database. Finally, make sure the code in your `RevenueChart` component (`/app/ui/dashboard/revenue-chart`) has been uncommented. I have a PR updating the course to make this more clear.

Let me know if the issue persists after trying these and I will look more into it :)

**Comment by DemaPy** [comment]
@tomas99batista ensure that [step 6](https://nextjs.org/learn/dashboard-app/setting-up-your-database) is correctly finished.

**Comment by delbaoliveira** [comment]
Hey @tomas99batista, any luck?

**Comment by tiuscia** [comment]
I do get a typescript issue in app/dashboard/page.tsx about the component <RevenueChart revenue={revenue}  /> 
<img width="871" alt="Screenshot 2024-01-13 at 9 00 49 PM" src="https://github.com/vercel/next-learn/assets/9962761/7e968c6f-51b0-45a4-94b6-f7b9a01fd0ac">
if you get this issue, you need to remove async from RevenueChart

**Comment by tiuscia** [comment]
actually in chapter 9, we do need to add async to the to components. so the only solution I found was using {/* @ts-expect-error Server Component */} is this the only solution correct?

**Comment by leerob** [comment]
Closing this one as stale, but please open a new issue if you are still having trouble here. Thank you!
