### ISSUE TITLE
ch-13 clarify error boundaries diff between dev / prod

### ISSUE THREAD

**Issue by LoiKos** [vercel/next-learn#403]
Hi ! 

I encountered a strange behaviour in chapter 13 with error boundary. I add the file `/app/dashboard/invoices/error.tsx`. It seems to correctly handle the error but at the same time there is still a problem : 

<img width="512" alt="Capture d’écran 2023-11-07 à 11 38 51" src="https://github.com/vercel/next-learn/assets/9548473/05d1e127-1c2c-45d0-ad6e-07e27aed2f13">

<img width="512" alt="Capture d’écran 2023-11-07 à 11 43 53" src="https://github.com/vercel/next-learn/assets/9548473/ebb63a67-9148-4317-a0ad-2f9d6bdc2062">

<img width="492" alt="Capture d’écran 2023-11-07 à 11 49 37" src="https://github.com/vercel/next-learn/assets/9548473/736767b8-1280-48cb-b41e-a2ffe3c089ff">

This happens only in dev mod, there is no error with the deployed version.

I don't know if this is expected or a bug but the actual behaviour seems a bit odd given the chapter descriptions. 

Is this expected ?

**Comment by StephDietz** [comment]
Hey @LoiKos, thanks for the feedback! This is expected behavior for Next.js. It shows the development mode error message in the development environment to help you quickly identify and debug issues. I see how this can be confusing, especially for people new to next. We have a PR adding clarifying language to the course to make this less confusing!
