### ISSUE TITLE
Chapter 8: "force-dynamic" behaving inconsistently

### ISSUE THREAD

**Issue by jpaveg** [vercel/next-learn#412]
With chapter 8 completed and the addition of `loading.tsx` to my `app/dashboard` directory, as well as the addition of `export const dynamic = "force-dynamic";` to my `app/dashboard/page.tsx` file, when I try navigating between pages, the dashboard page shows the `loading.tsx` component the FIRST time, then afterwards loads instantly, even though I have the 1 second timeout in my `fetchRevenue()` function within `app/lib/data.ts`. 

After leaving the tab alone for a short period of time, it starts working as expected, where whenever I navigate to /dashboard, it takes 1 second to load while waiting for the timeout within the `fetchRevenue()` function.

This is frustrating for someone who is trying to understand Nextjs - is there a way to prevent this one time behavior from occuring? 

**Reproduction:**
- Stop the dev server, clear localhost cookies + browser cache, then restart the dev server
- The first /dashboard page load will take build time + the timeout within the fetch function
- All immediate subsequent navigations back to the dashboard page will NOT be dynamically rendered, and the `fetchRevenue()` function is never called
- Wait a small period of time (30 seconds) without navigation, and the dashboard page will load dynamically every time

**Comment by delbaoliveira** [comment]
Hey @jpaveg, 

This describes the behavior of the [client-side router cache](https://nextjs.org/docs/app/building-your-application/caching), Next.js caches the dynamic routes for 30 seconds in your browser to prevent unnecessary calls to the server. On the initial visit, the page will take time to load as the data is fetched, on subsequent navigation (and within the 30-second window), navigation to the new page will be immediate as it reuses the router cache. 

You can clear the client cache by refreshing the page or using [`revalidatePath`](https://nextjs.org/docs/app/api-reference/functions/revalidatePath). 

This will become clearer in chapter 9, when adding Suspense, as you'll be able to visually see the loading skeletons on initial navigation. But not on subsequent navigation. You can also see it here, in the final demo: https://next-learn-dashboard.vercel.sh/dashboard

- Navigate to dashboard (initial visit with loading skeletons). 
- Visit invoices or customers
- Visit dashboard again (subsequent visit, no loading skeletons). 

Although the page may seem static because of the client cache. A simple way you can check the page is still dynamic is by adding `{Date.now()}` to your page and building your application locally. You should see a new date whenever you refresh, whereas a static page would not update after refreshing.
