### ISSUE TITLE
Chapter 15: Updating the login form typo, preventing error message.

### ISSUE THREAD

**Issue by cjboco** [vercel/next-learn#455]
Chapter 15, [Updating the login form](https://nextjs.org/learn/dashboard-app/mutating-data#updating-the-login-form)

When updating the `app/ui/login-form.tsx` file, you have a typo preventing the error message from displaying:

`Line 70: {state === 'CredentialsSignin' && (`

..should be...

`Line 70:  {state === 'CredentialSignin' && (`

You have an extra "s". I was actually getting a typescript error on this as well. Removing the "s", removed the typescript error.

[Edit: Type]

**Comment by delbaoliveira** [comment]
Hey @cjboco, thank you! It looks like there's a misspelling in the Server Action code snippet in the chapter. It should be `CredentialsSignin` with the s to match the Credentials provider in NextAuth.js. 

I'll update the chapter to make the correction, but in this case, you can use CredentialSignin since it matches the `authenticate` Server action.
