### ISSUE TITLE
blocked at charpter 6 links.map((link)

### ISSUE THREAD

**Issue by liwenz** [vercel/next-learn#508]
I follow https://nextjs.org/learn/dashboard-app/setting-up-your-database  until charpter 6.
In my visual code, show error, but compile fine.
github then vercel build error:
![2023-12-07 22_13_26-Window](https://github.com/vercel/next-learn/assets/19335957/4ed692ee-d348-4c47-a699-c1e0754b29a3)
line 19:{links.map((link) => {
the links and link show error. (same with my visual code)

github is:
https://github.com/liwenz/nextjs-dashboard

how do I continue?

**Comment by liwenz** [comment]
I also hope to setup database in local as my pc includes it

**Comment by alliyya** [comment]
You overwrote the whole file instead of copying the specific lines needed. (It looks like you rewrote the page with the snippet [here](https://nextjs.org/learn/dashboard-app/navigating-between-pages#the-link-component),. The `// ...` implies there was code omitted for clarity and to keep the snippet smaller.)

You should have:
```js
// Map of links to display in the side navigation.
// Depending on the size of the application, this would be stored in a database.
const links = [
  { name: 'Home', href: '/dashboard', icon: HomeIcon },
  {
    name: 'Invoices',
    href: '/dashboard/invoices',
    icon: DocumentDuplicateIcon,
  },
  { name: 'Customers', href: '/dashboard/customers', icon: UserGroupIcon },
];
```

Before the `NavLinks` function declaration.

**Comment by liwenz** [comment]
Thank you,alliyya.  following your code, the project build success, I continue my learning.
I wonder that /app/ui/dashboard/nav-links.tsx occurs at first at chapter 5. I only copy the code. I can't find your code somewhere.
