### ISSUE TITLE
Chapter 15: what's the purpose of "auth" in auth.ts?

### ISSUE THREAD

**Issue by iTiPo** [vercel/next-learn#628]
While studying chapter 15, I created three files: 
1. auth.config.ts  
2. middleware.ts   
3. auth.ts 

In `middleware.ts`, I am using the `authConfig` located in the `auth.config.ts` file in order to create a middleware function. Is that right?  
At the same time, in `auth.ts`, I'm exporting the `auth` function, but I don't see it being used anywhere. So, I don't understand why we are exporting it at all. Can you please explain this point?

**Comment by delbaoliveira** [comment]
Hey @iTiPo, the reason for the two files `auth.config.ts` and `auth.ts` is because `bcrypt` is not compatible with the Edge runtime. So the workaround at the time was to split the auth logic into two files. 

Just as an FYI, we're removing NextAuth chapter from the course as we have found that it can be overwhelming for beginners, and it doesn't reflect our current auth recommendations. If you'd like to learn more about auth, I've written a guide that goes through the principles of auth and what Next.js features to use, including guides from popular auth libraries: https://nextjs.org/docs/app/building-your-application/authentication
