### ISSUE TITLE
Chapter 1 - login arrow is enormous

### ISSUE THREAD

**Issue by richard-misiak-cg** [vercel/next-learn#635]
# Steps to reproduce

Following https://nextjs.org/learn/dashboard-app/getting-started

1. run 
    ```sh
    npx create-next-app@latest nextjs-dashboard --use-npm --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"
    cd nextjs-dashboard
    npm i
    npm run dev
    ```
1. go to http://localhost:3000/

The arrow icon is not scaled correctly:
![localhost_3000_](https://github.com/vercel/next-learn/assets/155737672/1b177fb5-9c14-4e3a-9c90-ff580b432240)

# system info

OS - windows 11
Browser - Chrome Version 123.0.6312.105 (Official Build) (64-bit)
```
> node -v
v20.11.1

> npm -v
npm -v
10.2.4

> npm list
+-- @heroicons/react@2.0.18
+-- @tailwindcss/forms@0.5.7
+-- @types/bcrypt@5.0.1
+-- @types/node@20.5.7
+-- @types/react-dom@18.2.14
+-- @types/react@18.2.21
+-- @vercel/postgres@0.5.0
+-- @vercel/style-guide@5.0.1
+-- autoprefixer@10.4.15
+-- bcrypt@5.1.1
+-- clsx@2.0.0
+-- dotenv@16.3.1
+-- eslint-config-next@14.0.0
+-- eslint-config-prettier@9.0.0
+-- eslint@8.52.0
+-- next@14.0.2
+-- postcss@8.4.31
+-- prettier-plugin-tailwindcss@0.5.4
+-- prettier@3.0.3
+-- react-dom@18.2.0
+-- react@18.2.0
+-- tailwindcss@3.3.3
+-- typescript@5.2.2
`-- zod@3.22.4
```

Related to https://github.com/tailwindlabs/heroicons/discussions/1120

**Comment by ed-nps** [comment]
@richard-misiak-cg I have the same issue and I get a 404 error when I click "Log in". Do you also get a 404?

**Comment by ed-nps** [comment]
I had the same issue. I found that the cause of this is that the global styles are not included. However, [chapter 2 of the tutorial](https://nextjs.org/learn/dashboard-app/css-styling) prompts us to include the global styles, and that fixes the issue. I'd suggest that `<ArrowRightIcon className="w-5 md:w-6" />` is removed from `page.tsx` so that it looks ok prior to the global styles being included (and this will mean that the app will reflect the [expected result from step 1](https://nextjs.org/_next/image?url=%2Flearn%2Fdark%2Facme-unstyled.png&w=3840&q=75).

**Comment by joelrb** [comment]
For all following the tutorial, what you get in the setup is a starter project. Ignore any error (like arrow, font, etc). You have to go through the tutorial and you'll find the fix for all those initial issues. So, be patient and follow the tutorial you'll find answers.

**Comment by leerob** [comment]
As mentioned, you'll set up the styles in the next chapter 😄
