### ISSUE TITLE
Following Next Learn course - not able to seed database

### ISSUE THREAD

**Issue by jonivrapi** [vercel/next-learn#766]
Hey guys,

I am following your next learn course on your website and made it to [here](https://nextjs.org/learn/dashboard-app/setting-up-your-database) before running into issues. The course seems out of date with how you are supposed to seed the database. There is no seed route that triggers this script anymore in the provided code, however there is a seed script. Took quite a bit of time to debug how this is supposed to run, but was able to solve it by adding a script to my package that references the env variables like so:

`"seed": "node -r dotenv/config ./scripts/seed.js"`

after this, running `npm run seed` successfully seeds the database. Please let me know if this is not the way you had intended for this to be done, and feel free to close the issue if so.

Thank you!

**Comment by HmnqL** [comment]
Had the same problem than you, I started the course yesterday and came here for help... also noticed that the repository one is supposed to clone for the course was updated YESTERDAY! and that the  folder was added in a commit YESTERDAY!! so i guess we both had bad timing xD try downloading again the repo and it should contain the seed folder inside /app

**Comment by A-Marotta** [comment]
Yeah I had the same issue and found the following workaround by deleting the seed directory, then committing my code to GitHub, which triggered a redeployment on Vercel. 

Chapter 6 outlines the steps to seed the data locally, so the seed directory and route.ts really don’t need to be committed and included as part of the build process which is triggering a fail because we do not have those psql env vars yet - the guide mentions deleting it after a successful seed anyway.

**Comment by anshal1** [comment]
Mine also not working but it's only happening in local when I hosted the app on vercel and navigated on `/seed` route in the action was successfully.

**Comment by IamSadiq** [comment]
The solution is just as mentioned by @jonivrapi, add "seed": "node -r dotenv/config ./scripts/seed.js" to your pacakage.json and run "npm run seed" to seed your database, also delete the "/seed" directory in app folder (if present) to fix the Vercel deployment errors. 

I believe the "localhost:3000/seed" option was revised due to the following error - "Type error: Top-level 'await' expressions are only allowed when the 'module' option is set to 'es2022', 'esnext', 'system', 'node16', or 'nodenext', and the 'target' option is set to 'es2017' or higher." in the "seed/route.ts" file.

Thanks @jonivrapi

**Comment by leerob** [comment]
We've updated the course to make this easier by moving the seed step to a Route Handler, so you can hit it from the browser.

**Comment by jonivrapi** [comment]
Thanks @leerob!
