### ISSUE TITLE
Chapter 6: Error conecting database

### ISSUE THREAD

**Issue by Lucio25** [vercel/next-learn#782]
I have this error when executing the npm run seed code, I don't understand why I followed the steps
C:\Users\Lucio\Desktop\Programacion\nextjs-dashboard\app\lib\placeholder-data.ts:143
export { users, customers, invoices, revenue };
^^^^^^

SyntaxError: Unexpected token 'export'

**Comment by nguyenmp** [comment]
Might help to share `placeholder-data.ts`.

I'm guessing a line above was deleted or edited accidentally because those lines are not 143.  https://github.com/vercel/next-learn/blob/main/dashboard/starter-example/app/lib/placeholder-data.ts#L147

Try replacing the file with what's on github and see if that fixes.

**Comment by leerob** [comment]
I am not able to reproduce, but you can work from the `final-example` backwards if you want to see the differences in your codebase.
