### ISSUE TITLE
npm ERR! Could not resolve dependency: npm ERR! peer react@"19.0.0-rc.0" from next@15.0.0-canary.56

### ISSUE THREAD

**Issue by scottfennell-toptal** [vercel/next-learn#802]
I'm on chapter 10.  Although my project still works locally, I started getting this error in the build logs in vercel:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@19.0.0-rc-f38c22b244-20240704
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-f38c22b244-20240704" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"19.0.0-rc.0" from next@15.0.0-canary.56
npm ERR! node_modules/next
npm ERR!   next@"15.0.0-canary.56" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /vercel/.npm/_logs/2024-07-12T11_41_02_681Z-eresolve-report.txt
npm ERR! A complete log of this run can be found in: /vercel/.npm/_logs/2024-07-12T11_41_02_681Z-debug-0.log
Error: Command "npm install" exited with 1
```

I can't seem to get past this.  Any suggestions?

**Comment by romu70** [comment]
This is the project which serves as the baseline for the Dashboard tutorial. And as a tutorial, its primary target is people which may not be expert at React and Next because they came here...to learn.

So why targeting RC versions of depencies which may be subject to changes and render this project unusable for the intended audience?

**Comment by romu70** [comment]
Here is how you can get a running project @scottfennell-toptal :
1. Clone the https://github.com/vercel/next-learn repository
2. Copy/paste the next-learn/dashboard/starter-example to where you want your learning project to be located
3. in the package.json file, remove the next, next-auth, react and react-dom lines
4. open a terminal in the project folder and run "npm install next next-auth react react-dom"
5. once done you should be able to run "npm run dev" and get something which starts

**Comment by leerob** [comment]
This tutorial is intentionally using the RC version, due to the impending stable release, so you don't have the learn that changes between v14 and v15. I can't reproduce issues deploying the final example in this repo to Vercel.

@scottfennell-toptal do you have multiple lockfiles? Are you using pnpm? If you could share your repository on GitHub, that would be very helpful. Thank you.

**Comment by michael-dixon** [comment]
I faced the same issue, although locally. Since google search sent me to this page, for others that might be facing this on initial create project - I removed the project files (rm -rf nextjs-dashboard), use node > 15 (nvm use 20), and then install pnpm gloabbly (npm install -g pnpm). I had done these on an older node version and it failed both with pnpm and npm. Once these were installed and confirmed, the dashboard project downloaded and built.

**Comment by benwatson528** [comment]
I can't run chapter one at the moment because of this same error. As a data engineer trying to pick up some front end skills then this is pretty frustrating. I've tried the suggestions on this page but haven't got anything working yet and I'm having to dive into a sea of `node_modules` `npm` `pnpm` and `package.json` that I probably shouldn't have to in chapter 1!

**Comment by benwatson528** [comment]
I can't even get chapter one working at the moment because of the issues mentioned here, this is pretty frustrating.

**Comment by leerob** [comment]
@benwatson528 can you try:

```bash
npm i -g pnpm
pnpm i
```

I hear you that having another package manager is confusing. Hopefully the performance improvements from pnpms faster installations and caching makes up for the one time setup 🙏

**Comment by gschauhan** [comment]
> 4\. npm install next next-auth react react-dom

You can use steps shared by @romu70 (direct link: https://github.com/vercel/next-learn/issues/802#issuecomment-2225807041)
It worked for me.

**Comment by benwatson528** [comment]
> @benwatson528 can you try:
> 
> ```shell
> npm i -g pnpm
> pnpm i
> ```
> 
> I hear you that having another package manager is confusing. Hopefully the performance improvements from pnpms faster installations and caching makes up for the one time setup 🙏

Hi @leerob I followed those steps in the tutorial to use `pnpm` but that's what leads to the error I'm seeing. I wasn't able to get the latest version of the tutorial working on Windows 11 with either `npm` or `pnpm`. I tried the suggestions in this thread and did a whole bunch of cache clearing but still no luck.

**Comment by leerob** [comment]
Can you share the error you are seeing in the console?

**Comment by benwatson528** [comment]
@leerob it's working now, I re-cloned and followed the steps from the tutorial like I'd done a couple of times the other night and this time it worked. Thanks!

**Comment by tlhakhan** [comment]
I'm running into a similar issue, following the dashboard-app tutorial: <https://nextjs.org/learn/dashboard-app/getting-started>.

Here are my steps so far to reproduce this.  I've deleted everything, rebuilt the container without cache, not sure where I'm going wrong here.

1. Use vanilla VS Code dev container (Debian bookworm).

```json
{
  "name": "Debian",
  "image": "mcr.microsoft.com/devcontainers/base:bookworm"
}
```

2. I installed nodejs and npm package.
```
vscode ➜ /workspaces/learn-nextjs (main) $ sudo apt update && sudo apt install -y npm nodejs
vscode ➜ /workspaces/learn-nextjs (main) $ node -v
v18.19.0
vscode ➜ /workspaces/learn-nextjs (main) $ npm -v
9.2.0
```

3. I ran the tutorial command (_without_ the `--use-pnpm` flag, because I don't want to use pnpm at the moment).

```
vscode ➜ /workspaces/learn-nextjs (main) $ npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example"
Need to install the following packages:
  create-next-app@14.2.5
Ok to proceed? (y) y
Creating a new Next.js app in /workspaces/learn-nextjs/nextjs-dashboard.

Downloading files from repo https://github.com/vercel/next-learn/tree/main/dashboard/starter-example. This might take a moment.

Installing packages. This might take a couple of minutes.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@undefined
npm ERR! Found: react@19.0.0-rc-f38c22b244-20240704
npm ERR! node_modules/react
npm ERR!   react@"19.0.0-rc-f38c22b244-20240704" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@">= 16" from @heroicons/react@2.1.5
npm ERR! node_modules/@heroicons/react
npm ERR!   @heroicons/react@"^2.1.4" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /home/vscode/.npm/_logs/2024-08-04T18_08_34_525Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vscode/.npm/_logs/2024-08-04T18_08_34_525Z-debug-0.log

Aborting installation.
  npm install has failed.

```

The error seems to indicate a dependency issue because the project wants to use the latest (rc) react version and heroicons doesn't like it?  I'm not sure how to fix this though, I tried the `--legacy-peer-deps --force` flags.

**Comment by tlhakhan** [comment]
I missed @romu70's response which includes a workaround.  https://github.com/vercel/next-learn/issues/802#issuecomment-2225807041

After running `npm run dev`, I see a somewhat broken landing page, unrelated to this issue.
<img width="612" alt="image" src="https://github.com/user-attachments/assets/09f31829-9d85-4568-8aed-7975942fb9a4">

**Comment by elidonner** [comment]
@jeremypeters suggestion fixed for me
>  $ pnpm remove next
> $ pnpm add next@latest

Error
```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
Came up in chapter 5 when using `'use client';`

**Comment by trevorgarr** [comment]
+1 getting the same issues as https://github.com/vercel/next-learn/issues/802#issuecomment-2267626425

**Comment by gmoniava** [comment]
@leerob Getting similar issue:
```
While resolving: undefined@undefined
Found: react@19.0.0-rc-f38c22b244-20240704
node_modules/react
  react@"19.0.0-rc-f38c22b244-20240704" from the root project

Could not resolve dependency:
peer react@">= 16" from @heroicons/react@2.1.5
node_modules/@heroicons/react
  @heroicons/react@"^2.1.4" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.
```

What is the way to resolve this given I want to use `npm`?

Here is command I used:
`npx create-next-app@latest nextjs-dashboard --example "https://github.com/vercel/next-learn/tree/main/dashboard/starter-example" 
`
I tried adding `--force` flag and  `--legacy-peer-deps` flags to above command but didn't help.

**Comment by itzamanjain** [comment]
removing next , react, react dom and installing again via pnpm and pnpm i fixed my issue

**Comment by leerob** [comment]
Good news, React 19 is now stable and updated here: https://github.com/vercel/next-learn/pull/946

**Comment by Dimaaasik** [comment]
Use
yarn create react-app my-app --template typescript
