### ISSUE TITLE
learn starter temp error : Invalid <Link> with <a>child

### ISSUE THREAD

**Issue by rashaabdulrazzak** [vercel/next-learn#98]
after working through the tutorial when I arrived to 
`https://nextjs.org/learn/basics/assets-metadata-css/polishing-layout`
when I run it I got the following error 
`Error: Invalid <Link> with <a> child. Please remove <a> or use <Link legacyBehavior>.
Learn more: https://nextjs.org/docs/messages/invalid-new-link-with-extra-anchor
`
the code for the layout has 3 places that have **Link**  and **a** tag under them. I resolved it by deleting the **a** tag. There is another way from next docs  to add **legacyBehavior** to the **Link**  and give the **a**  tag the id called link

**Comment by Thinura** [comment]
Hi @rashaabdulrazzak, I have created a PR for this issue. #99

**Comment by lgaspari** [comment]
My guess is that both the tutorial and this repository were meant to be used with **Next <13**. However the dependencies were recently updated to their most up-to-date version in #97 by @delbaoliveira. IMO, I don't think it's a good idea.

I have an open PR #92 that locks the `next` dependency version to `12.3.1` to use one if not the latest 12 version. Thoughts? Otherwise, the tutorial would need to be updated too. It worked seamlessly for my whole tutorial.

> Hi @rashaabdulrazzak, I have created a PR for this issue. #99

Hi @Thinura! Sorry, but that doesn't seem like a good solution since the idea is to get rid of nested `<a>` between `<Link>`, so you shouldn't use any wrapper underneath, see [here](https://nextjs.org/blog/next-13#breaking-changes).

**Comment by rashaabdulrazzak** [comment]
@lgaspari yeah I think this is a good idea or at least the tutorial should mention the version of Next.js to use

**Comment by leerob** [comment]
https://github.com/vercel/next-learn/pull/100
